services:
  - docker

script:
  - mkdir _site/
  - mkdir .asset-cache/
  - chmod 777 _site/
  - chmod 777 .asset-cache/
  - make buildimage build

after_success:
  - test $TRAVIS_BRANCH = "master" && make --quiet deploy
