# Site settings
title: Raphis website!
description: >
  My personal website and portfolio page.

url: "https://www.raphael.li"
github_username:  raphiz

permalink: /:categories/:title/

exclude:
    - docker/
    - README.md
    - Makefile
    - deploy.py
    - .travis.yml

host: 0.0.0.0

gems:
    - therubyracer
    - jekyll-assets
    - uglifier
    - jekyll-sitemap

markdown: redcarpet
highlighter: rouge

redcarpet:
  extensions: ["fenced_code_blocks", "tables", "with_toc_data"]
